---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ platformName }}-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      platformName: {{ platformName }}
  replicas: {{ replicas }}
  template:
    metadata:
      namespace: dev
      labels:
        platformName: {{ platformName }}
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
          name: web
        env:
        {% for ev in env_vars -%}
        - name: {{ ev.name }}
          value: {{ ev.value }}
        {% endfor %}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ platformName }}-service
  namespace: dev
spec:
  type: NodePort
  ports:
  - name: web
    targetPort: web
    protocol: TCP
    port: 80
    nodePort: 30005
  selector:
    platformName: {{ platformName }}
