---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: dev
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      namespace: dev
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbit
          image: rabbitmq:management
          ports:
            - containerPort: 15672
              name: management
            - containerPort: 5672
              name: amqp
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "status"]
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 15
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "ping"]
            initialDelaySeconds: 20
            periodSeconds: 60
            timeoutSeconds: 10
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: dev
spec:
  type: NodePort
  ports:
    - name: management
      targetPort: management 
      protocol: TCP
      port: 15672
      nodePort: 30001
    - name: amqp
      targetPort: amqp
      protocol: TCP
      port: 5672
      nodePort: 30002
  selector:
    app: rabbitmq
